spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///ISHMS-DB
    username: root
    password: root
  jpa:
    datasource:
        platform: org.hibernate.dialect.MYSQL8Dialect
    hibernate:
       ddl-auto: update
    show-sql: true
  
       
